services:
  tomcat:
    image: tomcat:10.1
    container_name: tomcat10
    ports:
      - "8080:8080"
    volumes:
      - ./external-config/tomcat/context.xml:/usr/local/tomcat/webapps/manager/META-INF/context.xml
      - ./external-config/tomcat/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - ./external-config/tomcat/tomcat-webapps/ROOT:/usr/local/tomcat/webapps/ROOT
      - ./external-config/tomcat/tomcat-webapps/docs:/usr/local/tomcat/webapps/docs
      - ./external-config/tomcat/tomcat-webapps/examples:/usr/local/tomcat/webapps/examples
      - ./external-config/tomcat/tomcat-webapps/host-manager:/usr/local/tomcat/webapps/host-manager
      - ./external-config/tomcat/tomcat-webapps/manager:/usr/local/tomcat/webapps/manager
    environment:
      - CATALINA_OPTS=-Xms512m -Xmx1024m
    restart: always

volumes:
  webapps:
    driver: local
